apiVersion: v1
kind: Service
metadata:
  name: qbot-service
  namespace: default
spec:
  selector:
    app: qbot
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: ollama
    port: 11434
    targetPort: 11434
  type: LoadBalancer  # For local access